// <auto-generated />
namespace Menoo.PrinterService.Infraestructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PrinterSchema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PrinterSchema));
        
        string IMigrationMetadata.Id
        {
            get { return "202203181831374_PrinterSchema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
